### ISSUE TITLE
Update default json.hpp

### ISSUE THREAD

**Issue by Adamtaranto** [PacificBiosciences/pbcopper#10]
As noted in Issue #9 pbcopper currently uses an older json spec which causes build to fail on some systems. I've just run into this issue again when installing unanimity. 

Suggest replacing default json.hpp with v2.0.1:
`
wget https://github.com/nlohmann/json/releases/download/v2.0.1/json.hpp -O pbcopper/include/pbcopper/json/internal/json.hpp
`

**Comment by pb-dseifert** [comment]
Fixed by updating to 3.1.2
